### ISSUE TITLE
supermemo.wiki search should display text only, not markdown

### ISSUE THREAD

**Issue by rajlego** [supermemo/SuperMemoAssistant.Documentation#50]
On the site, if you use the search function in the top left it for some reason shows markdown results, not just the text. To see this in action, search PDF and you'll get the following result:
![Screen Shot 2020-03-23 at 7 20 16 PM](https://user-images.githubusercontent.com/5921902/77323484-58e32280-6d3b-11ea-844d-d5100114a171.png)

**Comment by alexis-** [comment]
I have edited the title to better reflect the state of the Search function. Ideally we should reserve the word broken for these instances where there is really a serious issue that prevents using a feature at all.

**Comment by rajlego** [comment]
Got it. I was confused at first when searching for PDF on https://supermemo.wiki/#/ didn't yield the results I was looking for on https://supermemo.wiki/sma/#/ since it's not obvious that search would be separate, minor issue but if SuperMemo assistant used its own subdomain (sma.supermemo.wiki) the distinction might be a bit more obvious.
