### ISSUE TITLE
SuperMemo Intro Guide

### ISSUE THREAD

**Issue by rajlego** [supermemo/SuperMemoAssistant.Documentation#65]
[IR Strategies](https://github.com/supermemo/Documentation/issues/4)
[SuperMemo User Stories](https://github.com/supermemo/Documentation/issues/49)
[SuperMemo Guides](https://github.com/supermemo/Documentation/issues/2)
Alongside the above, we also should work on a good starting collection and videos for people to follow

**Comment by nikedinikedi** [comment]
turned this into epic
