### ISSUE TITLE
Add paragraph to backup guide about why cloud syncers (dropbox etc.) are not sufficient

### ISSUE THREAD

**Issue by bjsi** [supermemo/SuperMemoAssistant.Documentation#91]
Here's a paragraph I made from messages Alexis sent to the discord.

A common question people ask is "Why not use Dropbox or Google Drive for backups?". Admittedly, these are much more user friendly and require very little set up. However, there are a number of reasons why these services are inadequate for our purposes. Firstly, it is very easy to get something wrong, and corrupt your collection due to file locks. Previous backup methods relied on watching and killing processes in an effort to prevent this, but these are very inelegant solutions. Furthermore, syncing to a cloud provider pushes each file individually without any knowledge of how they are grouped together. If for some reason your cloud provider messes up the syncing, it might lead to nasty results. By contrast, the git push to server is an atomic transaction, meaning it either completely succeeds, or completely fails, there is no situation where your collection data gets partially backed up.

**Comment by alexis-** [comment]
Wow that's great ! Thank you.

**Comment by alexis-** [comment]
Added https://github.com/supermemo/Documentation/commit/2a41af903aff981e17f02bfe8e3e6593e957dd2c
